language: r

warnings_are_errors: true

packages: cache

sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env: CXX=g++-7 CC=gcc-7 AR=gcc-ar-7 RANLIB=gcc-ranlib-7 BUILD_TYPE=Release VERBOSE=1 CXX_FLAGS=-std=c++14

before_install:
  - mkdir -p ~/.R
  - echo "VkVSPS03CkNDPWdjYyQoVkVSKSAtc3RkPWMxMSAKQ1hYPWcrKyQoVkVSKQpTSExJQl9DWFhMRD1nKyskKFZFUikKRkM9Z2ZvcnRyYW4KRjc3PWdmb3J0cmFuCg==" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars
