language: r

warnings_are_errors: true

packages: cache

sudo: required

apt_packages:
  - libssh2-1-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - COMPILER=g++-7
        - CC=gcc=7
        - CXX=g++-7

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 100
  - mkdir -p ~/.R
  - echo "VkVSPS03CkNDPWdjYyQoVkVSKSAtc3RkPWMxMSAKQ1hYPWcrKyQoVkVSKQpTSExJQl9DWFhMRD1nKyskKFZFUikKRkM9Z2ZvcnRyYW4KRjc3PWdmb3J0cmFuCg==" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars
  - Rscript -e 'install.packages("git2r")'

env:
 global:
   - CRAN: http://cran.rstudio.com
