language: r
warnings_are_errors: true
sudo: required

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-4.9
        - CC=gcc=4.9
        - CXX=g++-4.9

before_install:
  - echo $HOME
  - mkdir -p ~/.R
  - echo "VkVSPS00LjkKQ0M9Z2NjJChWRVIpCkNYWD1nKyskKFZFUikKU0hMSUJfQ1hYTEQ9ZysrJChWRVIpCkZDPWdmb3J0cmFuCkY3Nz1nZm9ydHJhbgo=" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    - bob@rud.is
  irc:
    channels:
      - "irc.rud.is#builds"
    nick: travisci
