# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

internal_stream_in <- function(path) {
    .Call('ndjson_internal_stream_in', PACKAGE = 'ndjson', path)
}

internal_validate <- function(path, verbose) {
    .Call('ndjson_internal_validate', PACKAGE = 'ndjson', path, verbose)
}

