# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flatten_int <- function(lines) {
    .Call(`_ndjson_flatten_int`, lines)
}

stream_in_int <- function(path) {
    .Call(`_ndjson_stream_in_int`, path)
}

validate_int <- function(path, verbose) {
    .Call(`_ndjson_validate_int`, path, verbose)
}

